mysite/blog/urls.py
from django.conf.urls import patterns, url
from blog.rss import RssFeed

urlpatterns = patterns('',
    url(r'^$', 'blog.views.index', name='index'),
    url(r'^about/$', 'blog.views.about', name='about'),
    url(r'^contact/$', 'blog.views.contact', name='contact'),
    url(r'^register/$', 'blog.views.register', name='register'),
    url(r'^reg_result/$', 'blog.views.reg_result', name='reg_result'),
    url(r'^login/$', 'blog.views.login', name='login'),
    url(r'^login_result/$', 'blog.views.login_result', name='login_result'),
    url(r'^logout/$', 'blog.views.logout', name='logout'),
    url(r'^logout_result/$', 'blog.views.logout_result', name='logout_result'),
    url(r'^(?P<blog_id>\d+)/blogs/(?P<page_id>\d+)$', 'blog.views.blogs', name='blogs'),
    url(r'^(?P<post_id>\d+)/posts/$', 'blog.views.posts', name='posts'),
    url(r'^(?P<tag_id>\d+)/tags/(?P<page_id>\d+)$', 'blog.views.tags', name='tags'),
    url(r'^myblogs/$', 'blog.views.myblogs', name='myblogs'),
    url(r'^addnewblog/$', 'blog.views.addnewblog', name='addnewblog'),
    url(r'^addblog_result/$', 'blog.views.addblog_result', name='addblog_result'),
    url(r'^(?P<blog_id>\d+)/addnewpost/$', 'blog.views.addnewpost', name='addnewpost'),
    url(r'^addpost_result/$', 'blog.views.addpost_result', name='addpost_result'),
    url(r'^(?P<blog_id>\d+)/rmblog/$', 'blog.views.rmblog', name='rmblog'),
    url(r'^(?P<post_id>\d+)/rmpost/$', 'blog.views.rmpost', name='rmpost'),
    url(r'^(?P<post_id>\d+)/addnewtag/$', 'blog.views.addnewtag', name='addnewtag'),
    url(r'^(?P<post_id>\d+)/addtag_result/$', 'blog.views.addtag_result', name='addtag_result'),
    url(r'^(?P<tag_id>\d+)/rmtag/$', 'blog.views.rmtag', name='rmtag'),
    url(r'^(?P<post_id>\d+)/editpost/$', 'blog.views.editpost', name='editpost'),
    url(r'^editpost_result/$', 'blog.views.editpost_result', name='editpost_result'),
    url(r'^(?P<post_id>\d+)/addnewcomments/$', 'blog.views.addnewcomments', name='addnewcomments'),
    url(r'^(?P<post_id>\d+)/addcomments_result/$', 'blog.views.addcomments_result', name='addcomments_result'),
    url(r'^(?P<comments_id>\d+)/rmcomments/$', 'blog.views.rmcomments', name='rmcomments'),
    url(r'^(?P<blog_id>\d+)/rss/$', RssFeed(), name='rss'),
    url(r'^upload/$', 'blog.views.upload', name='upload'),
    url(r'^filepath/$', 'blog.views.filepath', name='filepath'),

)

mysite/mysite/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.conf import settings

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
	url(r'^blog/', include('blog.urls', namespace="blog")),
    url(r'^polls/', include('polls.urls', namespace="polls")),
    url(r'^admin/', include(admin.site.urls)),
)+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/blog/models.py
from django.db import models
import datetime
from django.utils import timezone
from django.contrib.auth.models import User

class Blog(models.Model):
    user = models.ForeignKey(User)
    name = models.CharField(max_length=200)
    cre_date = models.DateTimeField('date created')
    view_track = models.IntegerField(default=0)
    def __unicode__(self):  # Python 3: def __str__(self):
        return self.name

class Post(models.Model):
    blog = models.ForeignKey(Blog)
    title = models.CharField(max_length=200)
    body = models.TextField()
    pub_date = models.DateTimeField('date published')
    mod_date = models.DateTimeField('date modified')
    view_track = models.IntegerField(default=0)
    def __unicode__(self):  # Python 3: def __str__(self):
        return self.title

class Tag(models.Model):
    post = models.ForeignKey(Post)
    name = models.CharField(max_length=200)
    def __unicode__(self):  # Python 3: def __str__(self):
        return self.name

class Comments(models.Model):
    post = models.ForeignKey(Post)
    editor = models.CharField(max_length=200)
    body = models.TextField()
    pub_date = models.DateTimeField('date published')
    def __unicode__(self):  # Python 3: def __str__(self):
        return self.pub_date

mysite/blog/forms.py
from django import forms

class UploadFileForm(forms.Form):
    title = forms.CharField(max_length=50)
    file  = forms.FileField()

mysite/blog/views.py
from django.shortcuts import render, get_object_or_404, render_to_response
from django.http import HttpResponseRedirect, HttpResponse
#from django.template import RequestContext, loader
from django.core.urlresolvers import reverse
from django.contrib.auth import authenticate, login as auth_login, logout as auth_logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User

from blog.models import Blog, Post, Tag, Comments
from django.utils import timezone
import re
from xml.sax.saxutils import unescape
from .forms import UploadFileForm

def index(request):
    most_popular_blog = Blog.objects.order_by('-view_track')[:5]
    most_popular_post = Post.objects.order_by('-view_track')[:5]
    context = {'most_popular_blog': most_popular_blog, 'most_popular_post': most_popular_post}
    return render(request, 'blog/index.html', context)

def about(request):
    return render(request, 'blog/about.html')

def contact(request):
    return render(request, 'blog/contact.html')

def register(request):
    return render(request, 'blog/register.html')

def reg_result(request):
    username = request.POST['username']
    password = request.POST['password']
    try:
        user = User.objects.create_user(username, password=password)
    except:
        message = "Unexpected error:  Username already exits"
        return render(request, 'blog/reg_result.html', {
            'message': message,
        })
    else:
        message = "success"
        return render(request, 'blog/reg_result.html', {
            'message': message,
        })

def login(request):
    if request.user.is_authenticated():
        username = request.user.username
        return render(request, 'blog/login_result.html', {'username': username})
    else:
        return render(request, 'blog/login.html')

def login_result(request):
    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(username=username, password=password)
    if user is not None:
        if user.is_active:
            auth_login(request, user)
            username = request.user.username
            return render(request, 'blog/login_result.html', {'username': username})
        else:
            return render(request, 'blog/login_result.html', {
            'error_message': "disabled account.",
            })
    else:
        return render(request, 'blog/login_result.html', {
            'error_message': "Invalid login.",
        })


def logout(request):
    auth_logout(request)
    return HttpResponseRedirect(reverse('blog:logout_result'))

def logout_result(request):
    username = request.user.username
    return render(request, 'blog/logout_result.html', {'username': username})

def blogs(request, blog_id, page_id):
    blog = get_object_or_404(Blog, pk=blog_id)
    blog.view_track += 1
    blog.save()
    num_posts = blog.post_set.all().count()
    if num_posts%10:
        num_pages = num_posts/10
    else:
        num_pages = num_posts/10 - 1
    no = int(page_id)
    next = no + 1
    prev = no - 1
    if num_pages == no:
        postlist = blog.post_set.all().order_by('-mod_date')[no*10:]
    else:
        postlist = blog.post_set.all().order_by('-mod_date')[no*10:no*10+10]
    return render(request, 'blog/blogs.html', {'blog':blog, 'postlist': postlist, 'page_id':no, 'next':next, 'prev':prev,'num_pages':num_pages, 'num_posts': num_posts})

def posts(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    post.view_track += 1
    post.save()
    return render(request, 'blog/posts.html', {'post': post})

def tags(request, tag_id, page_id):
    the_tag = get_object_or_404(Tag, pk=tag_id)
    taglist = Tag.objects.filter(name=the_tag.name)
    allpostlist = []
    for t in taglist:
        allpostlist.append(t.post)
    num_posts = len(allpostlist)
    if num_posts%10:
        num_pages = num_posts/10
    else:
        num_pages = num_posts/10 - 1
    no = int(page_id)
    next = no + 1
    prev = no - 1
    for i in range(0,len(allpostlist)):
        for j in range(i,len(allpostlist)):
            if allpostlist[i].mod_date < allpostlist[j].mod_date:
                temp = allpostlist[i]
                allpostlist[i] = allpostlist[j]
                allpostlist[j] = temp
    if num_pages == no:
        postlist = allpostlist[no*10:]
    else:
        postlist = allpostlist[no*10:no*10+10]
    return render(request, 'blog/tags.html', {'the_tag':the_tag, 'postlist': postlist, 'page_id':no, 'next':next, 'prev':prev,'num_pages':num_pages, 'num_posts': num_posts})

def myblogs(request):
    if request.user.is_authenticated():
        username = request.user.username
        bloglist = Blog.objects.filter(user_id = request.user.id)
        return render(request, 'blog/myblogs.html', {'bloglist': bloglist, 'username': username})
    else:
        return render(request, 'blog/login.html')

def addnewblog(request):
    if request.user.is_authenticated():
        return render(request, 'blog/addnewblog.html')
    else:
        return render(request, 'blog/login.html')

def addblog_result(request):
    blogname = request.POST['blogname']
    b = Blog(user=request.user, name=blogname, cre_date=timezone.now(), view_track=0)
    b.save()
    return render(request, 'blog/addblog_result.html')

def rmblog(request, blog_id):
    b = Blog.objects.get(id = blog_id)
    if request.user.id == b.user.id:
        b.delete()
        return HttpResponse("This blog's been removed.  Please click back button.")
    else:
        return HttpResponse("You are not the owner of the blog.  Please go back and modify your own blog.")

def addnewpost(request, blog_id):
    b = Blog.objects.get(id = blog_id)
    if request.user.id == b.user.id:
        return render(request, 'blog/addnewpost.html', {'blog_id': blog_id})
    else:
        return HttpResponse("You are not the owner of the blog.  Please go back and modify your own blog.")

def addpost_result(request):
    title = request.POST['title']
    body = request.POST['body']
    body = re.sub(r'(http://\S+)', r'<a href="\1">\1</a>', body)
    body = re.sub(r'(https://\S+)', r'<a href="\1">\1</a>', body)
    body = re.sub(r'<a href=("\S+\.jpg")\S+</a>', r'<img src=\1>', body)
    body = re.sub(r'<a href=("\S+\.png")\S+</a>', r'<img src=\1>', body)
    body = re.sub(r'<a href=("\S+\.gif")\S+</a>', r'<img src=\1>', body)
    blogID = request.POST['blogID']
    b = Blog.objects.get(pk = blogID)
    p = b.post_set.create(title=title, body=body, pub_date=timezone.now(), mod_date=timezone.now(), view_track=0)
    return render(request, 'blog/addpost_result.html', {'blog_id': blogID})

def rmpost(request, post_id):
    p = Post.objects.get(id = post_id)
    if request.user.id == p.blog.user.id:
        p.delete()
        return HttpResponse("This post's been removed.  Please click back button.")
    else:
        return HttpResponse("You are not the owner of the post.  Please go back and modify your own blog.")

def addnewtag(request, post_id):
    p = Post.objects.get(id = post_id)
    if request.user.id == p.blog.user.id:
        return render(request, 'blog/addnewtag.html', {'post_id': post_id})
    else:
        return HttpResponse("You are not the author of the post.  Please go back and modify your own blog.")

def addtag_result(request, post_id):
    name = request.POST['name']
    postID = request.POST['postID']
    p = Post.objects.get(pk = postID)
    t = p.tag_set.create(name=name)
    return render(request, 'blog/addtag_result.html', {'post_id':postID})

def rmtag(request, tag_id):
    t = Tag.objects.get(id = tag_id)
    if request.user.id == t.post.blog.user.id:
        t.delete()
        return HttpResponse("This tag's been removed.  Please click back button.")
    else:
        return HttpResponse("You are not the owner of the post.  Please go back and modify your own blog.")

def editpost(request, post_id):
    p = Post.objects.get(id = post_id)
    blog_id = p.blog.id
    body = str(p.body)
    body = re.sub(r'<a href="(http://\S+)"\S+</a>', r'\1', body)
    body = re.sub(r'<a href="(https://\S+)"\S+</a>', r'\1', body)
    body = re.sub(r'<img src="(http://\S+)">', r'\1', body)
    body = re.sub(r'<img src="(https://\S+)">', r'\1', body)
    # body = re.sub(r'<a href="(https://\S+)"\S+</a>', r'\1', body)
    # body = re.sub(r'<a href="(https://\S+)"\S+</a>', r'\1', body)
    if request.user.id == p.blog.user.id:
        return render(request, 'blog/editpost.html', {'post': p, 'body': body})
    else:
        return HttpResponse("You are not the author of the post.  Please go back and modify your own blog.")

def editpost_result(request):
    title = request.POST['title']
    body = request.POST['body']
    body = re.sub(r'(http://\S+)', r'<a href="\1">\1</a>', body)
    body = re.sub(r'(https://\S+)', r'<a href="\1">\1</a>', body)
    body = re.sub(r'<a href=("\S+\.jpg")\S+</a>', r'<img src=\1>', body)
    body = re.sub(r'<a href=("\S+\.png")\S+</a>', r'<img src=\1>', body)
    body = re.sub(r'<a href=("\S+\.gif")\S+</a>', r'<img src=\1>', body)
    postID = request.POST['postID']
    p = Post.objects.get(pk = postID)
    p.mod_date = timezone.now()
    p.title = title
    p.body = body
    p.save()
    return render(request, 'blog/editpost_result.html', {'post': p})

def addnewcomments(request, post_id):
    if request.user.is_authenticated():
        return render(request, 'blog/addnewcomments.html', {'post_id': post_id})
    else:
        return render(request, 'blog/login.html')

def addcomments_result(request, post_id):
    editor = request.user.username
    body = request.POST['body']
    postID = request.POST['postID']
    p = Post.objects.get(pk = postID)
    t = p.comments_set.create(editor=editor, body=body, pub_date=timezone.now())
    return render(request, 'blog/addcomments_result.html', {'post_id':postID})

def rmcomments(request, comments_id):
    c = Comments.objects.get(id = comments_id)

mysite/blog/templates/blog/about.html
{% extends "base.html" %}

{% block content %}

<h3>This is final project of Open Source Tool</h3>

<h3>Project Name:  blOgShoT</h3>

<h3>Author:  Jizhou Li</h3>

{% endblock %}

mysite/blog/templates/blog/addnewblog.html
{% extends "base.html" %}

{% block content %}

<h2>Add a new blog</h2>
<form action="{% url 'blog:addblog_result' %}" method="post">
{% csrf_token %}
Blog Name:  <input type="text" name="blogname" /><br><br>
<input type="submit" value="add" />
</form>

{% endblock %}

mysite/blog/templates/blog/addnewcomments.html
{% extends "base.html" %}

{% block content %}

<h2>Add new comments</h2>
<form action="{% url 'blog:addcomments_result' post_id %}" method="post" id="addcomments">
{% csrf_token %}
<p>Comments body:</p>
<textarea rows="4" cols="50" name="body" form="addcomments"></textarea><br><br>
<input type="hidden" name="postID" value="{{ post_id }}"/><br>
<input type="submit" value="add" /><br>
</form>

{% endblock %}

mysite/blog/templates/blog/addnewpost.html
{% extends "base.html" %}

{% block content %}

<h2>Add a new post</h2>
<form action="{% url 'blog:addpost_result' %}" method="post" id="addpost">
{% csrf_token %}
Title:  <input type="text" name="title" /><br>
<input type="hidden" name="blogID" value="{{ blog_id }}"/><br>
<p>Post body:</p>
<textarea rows="4" cols="50" name="body" form="addpost"></textarea><br><br>
<input type="submit" value="add" /><br>
</form>

{% endblock %}

mysite/blog/templates/blog/addpost_result.html
{% extends "base.html" %}

{% block content %}

<h2>You've added a new post!</h2>

<!-- <a href="{% url 'blog:index' %}">Home</a> -->
<li><a href="{% url 'blog:blogs' blog_id 0 %}">Go to the blog</a></li>

{% endblock %}

mysite/blog/templates/blog/addtag_result.html
{% extends "base.html" %}

{% block content %}

<h1>You've added a new tag!</h1>

<a href="{% url 'blog:posts' post_id %}">Go back to the post</a>

{% endblock %}

mysite/blog/templates/blog/blogs.html
{% extends "base.html" %}

{% block content %}

<h2>Blog --- {{ blog.name }}</h2>
<p>This blog has been viewed {{ blog.view_track }} times.</p>
<a href="{% url 'blog:addnewpost' blog.id %}">Add a new post</a>&nbsp;&nbsp;&nbsp;&nbsp;
<!-- <a href="{% url 'blog:rss' blog.id %}">Turn to RSS</a>&nbsp;&nbsp;&nbsp;&nbsp; -->
<a href="{% url 'blog:rmblog' blog.id %}">Remvoe this blog</a><br>

<h3>Posts in this blog:</h3>
{% if postlist %}
<ul>
{% for post in postlist %}
    <li>
    	<h3>{{ post.title }}</h3>
    	<p>Post Body:&nbsp;&nbsp;&nbsp;&nbsp;{{ post.body|safe|slice:":500"|linebreaks }}<a href="{% url 'blog:posts' post.id %}">...more details</a></p>
    </li><br>
{% endfor %}
</ul>
{% else %}
    <p>No posts are available.</p>
{% endif %}

<!-- <a href="{% url 'blog:addnewpost' blog.id %}">add a new post</a><br>
<a href="{% url 'blog:rmblog' blog.id %}">remvoe this blog</a><br> -->

<!-- {% if page_id == 0 %}
<a href="{% url 'blog:blogs' blog.id next %}">next</a><br>
{% else %}
{% if page_id == num_pages %}
<a href="{% url 'blog:blogs' blog.id prev %}">prev</a><br>
{% else %}
<a href="{% url 'blog:blogs' blog.id prev %}">prev</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="{% url 'blog:blogs' blog.id next %}">next</a>
{% endif %}
{% endif %} -->

{% if num_pages == 0 %}
{% else %}
{% if page_id == 0 %}
<a href="{% url 'blog:blogs' blog.id next %}">next</a><br>
{% else %}
{% if page_id == num_pages %}
<a href="{% url 'blog:blogs' blog.id prev %}">prev</a><br>
{% else %}
<a href="{% url 'blog:blogs' blog.id prev %}">prev</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="{% url 'blog:blogs' blog.id next %}">next</a>
{% endif %}
{% endif %}
{% endif %}

{% endblock %}

mysite/blog/templates/blog/contact.html
{% extends "base.html" %}

{% block content %}

<h3>Author:  Jizhou Li</h3>

<h3>ID:  N14080567</h3>

<h3>email:  jl5092[at]nyu[dot]edu</h3>

{% endblock %}

mysite/blog/templates/blog/index.html
{% extends "base.html" %}

{% block content %}

<h2>Most popular blogs</h2>
{% if most_popular_blog %}
    <ul>
    {% for blog in most_popular_blog %}
        <li><a href="{% url 'blog:blogs' blog.id 0 %}">{{ blog.name }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No blogs are available.</p>
{% endif %}

<h2>Most popular posts</h2>
{% if most_popular_post %}
    <ul>
    {% for post in most_popular_post %}
        <li><a href="{% url 'blog:posts' post.id %}">{{ post.title }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No posts are available.</p>
{% endif %}

<!-- add new blog -->

<!-- <a href="{% url 'blog:addnewblog' %}">add a new blog</a><br> -->

{% endblock %}

mysite/blog/templates/blog/login_result.html
{% extends "base.html" %}

{% block content %}

{% if error_message %}
<h2><strong>{{ error_message }}</strong></h2>
<a href="{% url 'blog:login' %}">Please re-login.</a>
{% else %} 
<h2>You've been already logged in, {{ username }}</h2><br>
<a href="{% url 'blog:logout' %}">logout</a><br>
<a href="{% url 'blog:index' %}">go to home page</a><br>
<a href="{% url 'blog:myblogs' %}">go to myblogs</a><br>
{% endif %}

{% endblock %}

mysite/blog/templates/blog/logout_result.html
{% extends "base.html" %}

{% block content %}

{% if request.user.is_authenticated %}
<h1>Logout does not succeed</h1>
{% else %}
<h2>You've been already logged out.</h2><br>
{% endif %}
<a href="{% url 'blog:login' %}">re-login</a>

{% endblock %}

mysite/blog/templates/blog/myblogs.html
{% extends "base.html" %}

{% block content %}

<h2>{{ username }}'s blogs</h2>
{% if bloglist %}
    <ul>
    {% for blog in bloglist %}
        <li><a href="{% url 'blog:blogs' blog.id 0 %}">{{ blog.name }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No blogs are available.</p>
{% endif %}

<a href="{% url 'blog:addnewblog' %}">add a new blog</a>

{% endblock %}

mysite/blog/templates/blog/posts.html
{% extends "base.html" %}

{% block content %}

<h2>{{ post.title }}</h2>
<p>This post has been viewed {{ post.view_track }} times.</p>
<a href="{% url 'blog:addnewtag' post.id %}">Add a new tag</a>&nbsp;&nbsp;&nbsp;&nbsp;
<a href="{% url 'blog:editpost' post.id %}">Edit this post</a>&nbsp;&nbsp;&nbsp;&nbsp;
<a href="{% url 'blog:rmpost' post.id %}">Remvoe this post</a>&nbsp;&nbsp;&nbsp;&nbsp;<br>
<a href="{% url 'blog:blogs' post.blog.id 0 %}">Return to the blog</a>&nbsp;&nbsp;&nbsp;&nbsp;
<a href="{% url 'blog:addnewcomments' post.id %}">Add comments to this post</a>&nbsp;&nbsp;&nbsp;&nbsp;

<h3>tags of this post:</h3>
{% if post.tag_set.all %}
{% for tag in post.tag_set.all %}
    <a href="{% url 'blog:tags' tag.id 0 %}">{{ tag.name }}</a>&nbsp;&nbsp;
{% endfor %}
{% else %}
    <p>No tags are available.</p>
{% endif %}

<h3>body of this post:</h3>
{% if post.body %}
{{ post.body|safe|linebreaks }}
{% else %}
    <p>Body is null.</p>
{% endif %}

<h3>comments of this post:</h3>
{% if post.comments_set.all %}
{% for comments in post.comments_set.all %}
<ul>
    <li>{{ comments.body|linebreaks }}
    <p>post by {{ comments.editor }} at {{ comments.pub_date }}</p>
    <a href="{% url 'blog:rmcomments' comments.id %}">remove this comments</a>
    </li>
</ul>
{% endfor %}
{% else %}
    <p>No comments are available.</p>
{% endif %}

{% endblock %}

mysite/blog/templates/blog/upload.html
{% extends "base.html" %}

{% block content %}

<br><br>
<form action="{% url 'blog:upload' %}" method="post"
    {% if form.is_multipart %}enctype="multipart/form-data"{% endif %}>
{% csrf_token %}
{{ form.as_p }}
<input type="submit" value="Upload" />
</form>

{% endblock %}